### ISSUE TITLE
Anderer Name

### ISSUE THREAD

**Issue by MyIgel** [freifunk-ffm/ToDo-Liste#1]
Das teil ist definitiv zu sperrig :(

**Comment by oszilloskop** [comment]
So besser?

**Comment by skorpy2009** [comment]
ToDo-Liste reicht! Das ist schon in unserem Repo

**Comment by oszilloskop** [comment]
etwas Kontext ist nicht schlecht. 
Daher: **Todo-Liste**

**Comment by MyIgel** [comment]
K
