### ISSUE TITLE
(Wieder-)Inbetriebnahme einer Testdomain mit FFRL-Uplink

### ISSUE THREAD

**Issue by Adorfer** [freifunk-ffm/ToDo-Liste#11]
Titel ist vorläuft, bitte ggf. ändern.  

Matra: "Minimal-Effort."

Ziel: 
- 100% nach ['Eulenfunk-Doku'](http://eulenfunk.de)"
- Ein Konzentrator
- zwei Domains darin
- Feedback von Doku-Lücken/Fehlern
- Firmwarebuild dafür "ohne Sonderlocken"
- Integration (mit dem abweichenden Sitecode) auf die ffffmmap.

Projekt

**Comment by christf** [comment]
Am Montag hatte ich verstanden, dass ein Eulenfunk-Server in das bestehende FFM-Netz integriert werden solle.
Was meinst Du mit Domain?

**Comment by Adorfer** [comment]
Eine getrennte Broadcast-Domain, die aber auch auf der Map erscheinen soll. 
Parameter ist: kaum Broadcast/Batman-Traffic, nur ein Supernode. Und wenn die Router zu viel würden (d. h.  mehr als 100, dann sofort Split, also weitere supernode-VM) 

Ach ja, aktueller Batman, 11s und  auch fastd aktuell.

**Comment by christf** [comment]
Wie geht dann Kommunikation zwischen den Domänen?

Viele Grüße

Christof
-- 
Diese Nachricht wurde mit K-9 Mail gesendet.

**Comment by oszilloskop** [comment]
Ich stehe gerade etwas zwischen den Stühlen. 
@skorpy2009 hat es anscheinend gestern geschafft einen Supternode mit Up-Link zu FFRL aufzusetzen. Es handelt sich um fastd6, der auch schon testweise im Frankfurter Netz läuft. Wenn das Experiment erfolgreich sein sollte, dann bräuchten wir den, von Adorfer und mir mal angedachten Weg mit einer extra Unterkunftsdomaine, nicht mehr zwingend angehen.
fastd6 könnte dann diese Aufgabe übernehmen.
Bitte sprecht Euch ab.

**Comment by Adorfer** [comment]
> Wie geht dann Kommunikation zwischen den Domänen?

Könnte man mit Tinc oder GRE was bauen, um die RFC1918er-Netze quer zu routen.

**Comment by skorpy2009** [comment]
Also sowas wie ein Intra / Intercity VPN?
Wo für eigentlich eine neue Domäne, die nur du pflegen würdest?

**Comment by Adorfer** [comment]
Nee, allein möchte ich das nicht machen. 
Wichtig wäre mir nur eine Domain ohne Quertraffic und mit erträglichem Batman-Overhead.

**Comment by christf** [comment]
hm. mit quertraffic haben wir keine Probleme mehr seitdem wir die metriken von Batman angepasst haben. Der entsteht nur noch, wenn ein VPN ausfällt.

**Comment by Adorfer** [comment]
@christf Das ist mir schon klar.
Daher schlage ich das doch vor, eine Domain zu bauen, die nur auf L3 mit der bisherigen ffffm-domain zussammengeschaltet. 

Eben eine Domain mit weniger Altlasten (aktuelles Batman, aktuelles fastd, evtl L2TP, nur einen Supernode pro L2-Broadcast-Domain), sinnvollerweise auch mit voll funktionsfähigem Public-IPv6.

**Comment by christf** [comment]
Zeit für Entscheidungen. Wollen wir da _jetzt_ so viel investieren, das umsetzen? Schritte wären:
- [ ] Domainsplit
- [ ] Aufbau einer neuen Domain
- [ ] Aufbau einer neuen Firmware für diese neue Domain
- [ ] Zusammenschaltung der Domains per routing
- [ ] Kommunikation, wer wo in welcher Domain sein sollte.
- [ ] Umzug der in dem Bereich bestehenden Nodes

hab ich was vergessen?

**Comment by skorpy2009** [comment]
Dagegen wegen dem erhöhten Aufwand + müsste in einer Automatisierung sein. Aber großes Pro: weg von OpenVPN

**Comment by oszilloskop** [comment]
Kann das hier geschlossen werden?
