### ISSUE TITLE
Prometheus

### ISSUE THREAD

**Issue by skorpy2009** [freifunk-ffm/ToDo-Liste#12]
- [ ] Fastd5 neu installieren lassen
  - [ ] IPv6 extern
  - [x] Name: Prometheus.ffm.freifunk.net
  - [x] frisches Debian 8.*
- [ ] Puppet Profil für Prometheus erstellen
  - [ ] wie automatisch entsteht die config?
- [ ] Prometheus DNS umziehen

**Comment by christf** [comment]
Damit wird die Map entlastet.

**Comment by christf** [comment]
der puppetmaster kennt nun das fastd5-Zertifikat nicht mehr.

**Comment by christf** [comment]
Neuaufbau von fastd5 ist angefragt.

**Comment by christf** [comment]
Erweiterung der Kapazität erfolgt ende Februar / Anfang März

**Comment by skorpy2009** [comment]
Erfahrung zeigt, das eine dedizierte Maschine sich für die Leistungsüberwachung und das Monitorring empfiehlt. 
Die Daten der aller Knoten und Server / VMs / Services sind doch Verhältnismäßig viel. Statistik > 10GB für 15 Tage.

**Comment by skorpy2009** [comment]
Wird auf dem "neuen" Server aufgesetzt
