### ISSUE TITLE
enable IPv6 over FFRL

### ISSUE THREAD

**Issue by skorpy2009** [freifunk-ffm/ToDo-Liste#15]
https://github.com/freifunk-ffm/packages/pull/10
IPv6 kommen nicht durch wenn sie nicht in der Site Conf als Src stehen...

**Comment by christf** [comment]
wird denn das ffrl ipv6 schon im netz verteilt? Wenn das nicht geroutet wird, dann führt das zu zahlreichen problemen. => der radvd darf dsa bitte bis die neue Firmware da ist nicht verteilen.

**Comment by oszilloskop** [comment]
@skorpy2009 Was und wie bedatet, möchtest Du gerne in der site.conf sehen?

**Comment by skorpy2009** [comment]
@christf ich denke der radvd sollte das gar nicht auf den nodes verteilen, sondern nur die Zentralen radvds die auch das routing machen, wie sollen die nodes sonst wissen wo hin mit dem traffic, da sie sich ja selber announcen und so....

**Comment by christf** [comment]
kann man so machen, dann haben die clients keine ffrl ips.

**Comment by christf** [comment]
https://github.com/freifunk-ffm/packages/pull/10 ist gemerged. ist noch etwas im rahmen dieses issues zu erledigen? @skorpy2009

**Comment by skorpy2009** [comment]
Mit der neuen Dev scheint es zu funktionieren...
