### ISSUE TITLE
direct exit

### ISSUE THREAD

**Issue by skorpy2009** [freifunk-ffm/ToDo-Liste#16]
Das direct exit Script müsste so eingerichtet werden, das es (kurz) nach dem booten ausgeführt wird und nicht nur durch dem Cron Job.

**Comment by t-8ch** [comment]
Am besten einen systemd timer + unit und dann können die anderen skripte einfach davon abhängen

**Comment by christf** [comment]
wollen wir für sowas ein puppet-label haben?

**Comment by MyIgel** [comment]
Klingt gut

**Comment by christf** [comment]
@t-8ch hattest du das nicht schon probiert?

**Comment by skorpy2009** [comment]
@t-8ch has done quit some work: https://github.com/freifunk-ffm/supernode_puppet/commit/229f971ed0863b56ec0b4921346ca68abfaf1704

**Comment by skorpy2009** [comment]
still doesn't work =>

```
root@fastd2:~# sysctl -a | grep net.nf_conntrack_max
net.nf_conntrack_max = 65536
```

after reboot

**Comment by christf** [comment]
was ist hier der nächste schritt?

**Comment by skorpy2009** [comment]
scheint stabil zulaufen
