### ISSUE TITLE
umzug des download-servers auf myigels dl-host mit viel speicherplatz

### ISSUE THREAD

**Issue by christf** [freifunk-ffm/ToDo-Liste#19]
der uber hat zu wenig speicherplatz.
@MyIgel help!

**Comment by MyIgel** [comment]
@christf: Was darf ich tun? Sieht man sich mal im HQ?

**Comment by MyIgel** [comment]
ToDo:
* Cron auf dem reverse proxy einrichten
* Https-Config optimieren

**Comment by christf** [comment]
gegenwärtig zeigt https://dl.ffm.freifunk.net eine weiße Seite.

**Comment by oszilloskop** [comment]
bei mir nicht. Getestet mit Chrome und Safari unter OS X.

**Comment by MyIgel** [comment]
Bei mir klappt es auch problemlos, ich schau mir die config noch mal an :)

**Comment by christf** [comment]
Tut mir leid, es liegt an meinen Browser. Wir Kriege ich möglichst schmerzarm ein ff profil beruhigt und Caches gelöscht? Das war früher irgendwie leichter...

**Comment by christf** [comment]
@myigel sind die Aufgaben cron und https Optimierung noch relevant?

**Comment by MyIgel** [comment]
Leider ja, muss da noch dinge vereinheitlichen (dl & wiki)

**Comment by oszilloskop** [comment]
Es gibt noch eine Handvoll alte Stable-, Test- und Dev-Router im Netz. Diese greifen teilweise noch auf 1.updates.services.ffffm zu. Auch diese müssen wir irgendwann, irgendwie einfangen.

Kann daher ein DNS-Eintrag erstellt werden, der 1.updates.services.ffffm mit der IP des DL-Servers von @MyIgel auflöst?

**Comment by MyIgel** [comment]
@oszilloskop: done

**Comment by MyIgel** [comment]
Cron ist eingerichtet & ssllabs zeigt ein A+
