### ISSUE TITLE
Unter der allgemeinen Freifunk-Karte tauchen keine FFM-Knoten auf

### ISSUE THREAD

**Issue by oszilloskop** [freifunk-ffm/ToDo-Liste#2]
Unter der der allgemeinen Freifunk-Karte ( https://www.freifunk-karte.de ) tauchen die Frankfurter Knoten nicht mehr auf.

Hinweis:
Unsere Freifunk-API-JSON-Datei ist hier zu finden: https://api.ffm.freifunk.net/ff-frankfurt.json 
Unsere Node-JSON ist hier abgelegt: https://map.ffm.freifunk.net/hopglass/nodes.json

Jürgen kümmert sich.

**Comment by Adorfer** [comment]
Die Api verweist derzeit (korrekt) auf 
https://api.ffm.freifunk.net/ff-frankfurt.json

Die Einträge dort sehen gut aus. 
Und unter den URLs gibt es auch "frisch" Daten. 

```

"nodeMaps": [
    {
      "url": "https://map.ffm.freifunk.net/",
      "interval": "5",
      "technicalType": "hopglass",
      "mapType": "geographical"
    },
    {
      "url": "https://map.ffm.freifunk.net/hopglass/nodes.json",
      "interval": "5",
      "technicalType": "nodelist",
      "mapType": "list/status"
    }
  ],
```

**Comment by oszilloskop** [comment]
Ich habe den Tino angeschrieben.

**Comment by oszilloskop** [comment]
Anbei die Antwort vom Tino. 
```
Hallo,

euer API-File weist
https://map.ffm.freifunk.net/hopglass/nodes.json
als nodelist aus.
das ist aber kein nodelist format.
Damit kann der parser das nicht verarbeiten, weil ihm praktisch Melonen
als Birnen verkauft werden.

könnt ihr das berichtigen?
Entweder tatsächlich nodelist liefern, oder aber ffmap oder meshviewer
dran schreiben?
```

Jetzt bräuchte ich doch etwas Hilfe!

**Comment by oszilloskop** [comment]
Link der Node-JSON von
https://map.ffm.freifunk.net/hopglass/nodes.json
auf
https://map.ffm.freifunk.net/hopglass/nodelist.json
geändert.

Siehe https://github.com/hopglass/hopglass-server#possible-webserver-queries

Test läuft...

**Comment by eberhab** [comment]
nodelist.json sollte das Problem beheben
https://github.com/freifunk-ffm/map-server-config/blob/master/TODO.md

**Comment by oszilloskop** [comment]
Die Lücke über Frankfurt ist gestopft.

![bildschirmfoto 2016-10-05 um 13 36 24](https://cloud.githubusercontent.com/assets/1434390/19111672/23975c42-8b01-11e6-8d64-b7fbfe667eef.png)
