### ISSUE TITLE
Umzug des fffffmmapserver von netcup auf eulenfunk-Proxmox

### ISSUE THREAD

**Issue by Adorfer** [freifunk-ffm/ToDo-Liste#20]
ich habe mich gestern (als die Kiste nicht lief und auch auf der VNC-Konsole nicht ansprechbar war) nach dem Reset das erste mal "im Produktivbetrieb" dort eingelogt: Die Load ist nicht tragbar, das System ist schlicht völlig überlastet. 

Vorschlag: 

1) Umzug des Systems auf "dags3" (Eulenfunk). DD-job? Oder neu aufsetzen?
2) Freigabe der Mini-VM für Babel-Map-Versuche. (Alternativ zu 2: Einstampen der netcup-vm komplett)

**Comment by christf** [comment]
@skorpy2009 und ich hatten noch eine weitere Alternative entwickelt, ich fänd es gut, wenn wir die mal alle hier reinpacken und dann gemeinsam entscheiden.

Die Idee war, den prometheus auszulagern auf eine andere VM (die wir im Moment nicht für trafficlastige Dinge nutzen können, die aber genügend CPU und RAM-Kapazitäten hat) und den Rest auf der Map laufen zu lassen.

Insgesamt spielt dann noch eine Rolle wie man mit der Map für das babel-Testnetz umgehen möchte. Nachdem ich @Adorfer  um Hilfe gebeten hatte kam noch die Idee auf, sowohl das Frankfurter FF-Netz als auch das Testnetz auf der gleichen Map zu betreiben, damit man nach außen hin nicht wieder das Chaos herstellt, dass wir beim Meshviewer-Umzug hatten. Das macht dann folgende Entscheidungen erforderlich:

1. Betreibt man für das Testnetz eine separate Map? <= Hier ist meine Meinung mittlerweile, dass  wir versuchensollten das zu vermeiden

2. Auf welcher Infrastruktur läuft die Map?
Hier gibt es 2 Ansätze:
a) Der gesamte Map-Stack läuft in der selben VM
b) einzelne Komponenten werden ausgelagert.

Zu (2) hab ich noch keine Meinung gebildet. Was sind Vor- und Nachteile von 2a/2b)?

**Comment by Adorfer** [comment]
Die EulenfunkMap-Instanz ist schlecht vergleichbar, da dort mehrere Domains gerechent werden

- VM hängt in etwa 15 verschiedenen Batman-Netzen per Fastd
- Rendert 15 verschiedene "lokale" Hopglas-Server, zum großen Teil auf "eigenen" Domains
- Generiert etwa 5 "Sammelkarten" community-Übergreifend. 
- Der Hauptlast kommt aus dem Grafana. 

siehe https://github.com/eulenfunk/mapconfig/blob/master/sites

Was die frisst: Nicht wenig, es sind aber eben auch >1500 Knoten
![grafik](https://cloud.githubusercontent.com/assets/10302493/20055932/e1c37a74-a4e3-11e6-9d23-e5c8b443f447.png)

![grafik](https://cloud.githubusercontent.com/assets/10302493/20056002/48c2c004-a4e4-11e6-856e-ebb657234d22.png)

![grafik](https://cloud.githubusercontent.com/assets/10302493/20056020/602a7ade-a4e4-11e6-8bcd-d143101aaa13.png)

**Comment by Adorfer** [comment]
VM ist aufgesetzt auf dags1, vorerst mit 2 Kernen, 20GB Platte und 4GB RAM. 
Falls das nicht reicht, dann müssen wir die IP nochmal ändern, da wir die nicht "mitnehmen" können. 
**Falls also mehrere dns-Namen auf das Ding zeigen, bitte ein A-Record machen und da dann die anderen als C-Name hinzeigen lassen.**

**Comment by Adorfer** [comment]
P.S. 
IPv4: 5.196.175.55 	DE	
**hostroute(!)** 51.254.47.239 
reverse (können wir ändern) ns3016549.ip-51-254-47.eu	
ipv6: 2001:41d0:1008:7ef::c3ba
mac: 02:00:00:d7:c3:ba

**Comment by skorpy2009** [comment]
@Adorfer was ist den das default gateway IPv6?

**Comment by skorpy2009** [comment]
netmask IPv6: 56

**Comment by skorpy2009** [comment]
Prometheus und Alertmanager sind installiert und die ersten Configs sind erstellt

**Comment by Adorfer** [comment]
ipv6: 
# eisen 2001:41d0:1008:7ef::/64
# localmac 02:00:00:d7:c3:ba
# localipv6  2001:41d0:1008:7ef::d7:ceba/128
# defaultroute via 2001:41d0:1008:07ff:ff:ff:ff:ff

**Comment by Adorfer** [comment]
Wenn der "alte" (Netcup VM) frei ist/wird, bitte Bescheid geben. Danke.

**Comment by skorpy2009** [comment]
Prometheus & Grafana ist auf dem neuen System installiert, läuft akzeptabel solange man nicht alle Grafen der Knoten zeichnet

**Comment by Adorfer** [comment]
Damit mache ich den Netcup dann platt, OK?

**Comment by skorpy2009** [comment]
Nein, nur Prometheus ist dort!
Hopglass Stack sollte da aus Performance Gründen nicht drauf.

**Comment by Adorfer** [comment]
Bis zum 25.04.2017 (deadline) muss der alte Server (46.38.238.147) geräumt sein, da läuft der Vertrag aus. 
Ich hätte aber diverse andere Maschinen anzubieten, die auchmehr Wumms haben. 
Alterantiv, prüft bitte mal ob das Prometheus auch auf den neuen Server passt. 
Da müsste Luft sein.

**Comment by christf** [comment]
Wer kann zusammenfassen was jetzt wo läuft?
@skorpy2009 soweit ich weiß hast Du den Kram dankenswerterweise zuletzt mit @t-8ch repariert.

Was läuft wo und welcher Dienst fällt am 25.4. weg?
Welche Voraussetzungen braucht der auf einer neuen Maschine?

**Comment by Adorfer** [comment]
![grafik](https://cloud.githubusercontent.com/assets/10302493/24269962/8ffde058-1013-11e7-9965-db29e66ff14a.png)

Was auf der Maschine läuft: Keine Ahnung. Bitte prüft es bitte selbst, ich habe da den Überblick verloren. 
Faktisch fällt diese Kiste weg.

**Comment by skorpy2009** [comment]
Wahram wollte das alles aufschreiben, ich habe ihm das grob aufgeschrieben + erklärt

Wir brauchen $Debians:

- pro Netz Architektur eine VM mit dem jeweiligen Mesh Protokoll mit "yanic" https://github.com/FreifunkBremen/yanic
- einen InfluxDB (Blech zu mieten ist zu teuer also eine VM) mit allem; schnell groß viel...
- eine Prometheus Instanz auf einer guten schnellen VM fürs Monitoring
- eine Grafana Instanz, wo auch immer
- N Frontend VMs die den Ranz mit HTTP/2 und gzip und so ausliefern
schön wäre
- iwas was Tiles rendert und cached; da rendern ressourcen intesiv=> cachen und mit HTTP/2 ausliefern....

**Comment by christf** [comment]
Nach einem IRC Gespräch beantworte ich meine Frage selbst:
* Grafana fällt weg und muss ersetzt werden (eigene VM)
* hopglass fällt weg und wird durch yanic ersetzt (eigene VM je mesh-Protokoll), also 2 VMs.
* Prometheus fällt weg und muss auf einer VM ersetzt werden
* InfluxDB ist neu und wird wegen yanic benötigt. Braucht eine VM.
* Das Frontend fällt weg und muss ersetzt werden (HTTP2/gzip...)
* Tiles rendern fällt nicht weg, wäre aber optional neu.

**Comment by christf** [comment]
Jetzt der nächste Schritt:
Wir wollen 5 VMs einrichten. Jetzt betrachten wir mal, wie die ausgestattet sein müssen. Jeweils RAM und vCPU. Was wird benötigt?

**Comment by christf** [comment]
Wieder aus der IRC-Diskussion wird folgende Ausstattung vorgeschlagen:
* Grafana: 
* Yanic: 1GB RAM, 2 vCPU, 10GB HDD
* Prometheus: 
* InfluxDB: >=4GB RAM, 4vCPU, 50GB HD
* Frontend: >=512MB Ram, 2  vCPU, 10GB HDD
* optional: Tiles:


Die Liste wird vervollständigt.

**Comment by christf** [comment]
nächster Schritt: Wo wird welcher Dienst gehostet? @Adorfer kannst Du bei dieser Frage helfen?

**Comment by Adorfer** [comment]
> Wo wird welcher Dienst gehostet? @Adorfer kannst Du bei dieser Frage helfen?

Das weiss ich nicht. 
Ich habe keinen Login auf die Maschinen. 
Ich kann Euch nur sagen, welche Maschinen welche IP-Adressen, Resourcen und Mac-Adressen haben. 
Falls dazu Unklarheiten bestehen sollten: 

Wegfall am 25.04.2017: 

![grafik](https://cloud.githubusercontent.com/assets/10302493/24524157/e3eea21a-1595-11e7-8a15-4137eb71f4f9.png)
![grafik](https://cloud.githubusercontent.com/assets/10302493/24524192/f98f28b0-1595-11e7-9cae-d66b08b21c0f.png)


Weiterbestehen: 
![grafik](https://cloud.githubusercontent.com/assets/10302493/24524272/3676a1d6-1596-11e7-889c-d721268f86bd.png)
Mehr CPU könnte der bekommen, ggf auch etwas mehr HDD, Problem wäre jedoch "Mehr Ram".

**Comment by christf** [comment]
@Adorfer sorry, die Frage war unklar formuliert. Ich versuchs nochmal:
Wo können zukünftig die Dienste mit dem Ressourcenbedarf gehostet werden?
Das sollten wir jetzt zusammentragen.

**Comment by christf** [comment]
Die Dienste:
* influxdb, prometheus haben auf einem uvensys-host ein Heim gefunden
* Das Frontend und Grafana werden auf der gleichen VM auf dem Blech des DL-Servers laufen
* yanic wird auf dem uber-host in einem lxc ausgeführt werden

**Comment by MyIgel** [comment]
## Webserver -> parallel zu f1 / dl
Webfrontend / Ausgabe der Daten / Caching
* Proxy
* Grafana
* Meshviewer
* Optional: Tilecache

## Yanic -> Uber? hat kaputtes v6
Daten von den Nodes holen
* Benötigt FF Netz

## InfluxDB -> Uvensis
Nodedaten speichern
* 4 Kerne
* 16G RAM
* 250GB HDD

## Prometheus -> Eulenfunk ?
Monitoring
* 50GB-100GB HDD
* 4GB RAM
* Unabhängig vom rest
* Graphen im Grafana?

**Comment by Adorfer** [comment]
@christf Du hattest mir im IRC einige Fragen gestellt gestern. 
Ehrlich gesagt vermag ich keine zu beantworten, da ich die das derzeitige Setup nicht kenne. Da ich nicht weiss, auf welchem Host derzeit was gemacht wird. Geschweige denn, dass ich weiss, wo es welche Probleme gibt: Ich kann nichts sinnvoll vorschlagen. 
Ich bin wirklich an der Stelle eines Hosters, Ich kann der/den VMs Resourcen einstellen und Logins machen, ggf. Rettungsmedien einlegen und Sachen dumpen. 
That's it. 

Was die Resourcen anbelangt: 50-100GB HDD ist der Knackpunkt. Denn jede HDD muss auch in den Backup-Plan. Und Backup ist IO-Load. Das kann man ionicen, nur dann muss man schauen, dass das Backup in einer Woche für alle VMs fertig wird... 
Will sagen: 50GB wären so mein gefühltes Limit.

**Comment by christf** [comment]
hm. inwiefern man ein tägliches/wöchentliches oder monatliches backup braucht, kann man an der stelle glaub ich philosophisch diskutieren. aber die größenordnung passt ja schonmal. :)
Wer hat denn schon logins?

**Comment by Adorfer** [comment]
Der Host in der Eulenfunk-Domain (IPv4 5.196.175.55) heisst derzeit "monitoring.ffm.freifunk.net"
Ich habe dort heute Früh auf Geheiß ein Backup vom 10.04.2017 eingespielt. 
Was ihr mit dem System macht: Bitte formalisiert/dokumentiert es hier irgendwo. Damit ich die Chance habe, "merkwürdige Betriebszustände" zu erkennen. (Sofern das gewünscht ist.)

wir könnnen aber gern auch ein neues Issue draus machen.
