### ISSUE TITLE
Gluon 2016.2 und BROKEN target

### ISSUE THREAD

**Issue by ctr49** [freifunk-ffm/ToDo-Liste#21]
Für Dev/Test Images wäre es ganz gut, mal den 2016.2 branch zu mergen und im build script "BROKEN=1" zu aktivieren um auch mit ungetesteter Hardware arbeiten zu können.

**Comment by oszilloskop** [comment]
Zu Gluon 2016.2:
Da wir uns bisher von der DEV über die TEST zur STABLE hocharbeiten, ist dieses noch nicht wirklich geschehen.
Die DEV ist aber seit ca. 1 Woche auf Gluon 2016.2.x. 
Es gibt noch Abstimmungsarbeiten mit unseren eigenen Packages. Da muss geschaut werden, ob Funktionalitäten mit der 2016.2.x nicht plötzlich doppelt vorhanden sind.
Selber bauen der DEV sollte aber auch schon möglich sein.

Zu BROKEN=1:
Das ist so ein Ding. Ich glaube es ist keine gute Idee dieses in der STABLE zu aktivieren. Weil dann ist die nicht immer stabil :o) 
Wenn eine neue STABLE released wird, wird es aber auf jeden Fall eine funktionsidentische DEV mit BROKEN Devices gebe.

**Comment by oszilloskop** [comment]
Nochmal zu BROKEN=1:
Klar, für das Bauen von "Homebrew" Versionen kann das In der site.mk der jeweiligen Branches natürlich jetzt schon umgesetzt werden.

**Comment by ctr49** [comment]
Ah ok, hatte nicht gesehen, dass das schon in DEV ist. Durch die unterschiedlichen Versionen blickt man nicht sofort durch. Ich habe nur [darauf](https://github.com/freifunk-gluon/gluon/pull/802) gewartet.
BROKEN=1 nicht _ungeprüft_ nach STABLE zu nehmen macht natürlich Sinn, aber BROKEN=1 heißt nicht zwangsläufig, dass es nicht geht, sondern nur, dass es nicht intensiv getestet worden ist. Wenn man eine neue Plattform mit DEV und TEST Images ordentlich testen kann und alles funktioniert, sollte auch nichts dagegen sprechen, für ein geprüftes Target auch BROKEN=1 im STABLE zu aktivieren. Und im Gegensatz zu DEV vs. TEST vs. STABLE bedeutet das reine Vorhandensein eines Images für eine bestimmte Plattform auch dann keinen Rückschritt, wenn es tatsächlich mal nicht geht: Solange es gar kein Image gibt, funktioniert auch nichts ;-)

**Comment by oszilloskop** [comment]
Da müssen wir uns mal Gedanken machen, wie wir eine Broken parallel anbieten können. So zu sagen als second source.

Hintergrund:
- Es gibt Leute wie Dich, die haben da bereits eine Hardware rumliegen und testen einfach mal ob es klappt. 
- Es gibt Leute, die haben noch keinen Router, schauen bei unseren Stable-Releases nach und kaufen sich dann einen vermeintlich unterstützten Router für ihre Ansprüche. Gerade mit teueren 2,4/5GHz-Routern kann man da auf die Nase fallen.
 
Aber wenn wir irgendwann mal unseren Firmwareselektor haben (siehe #3), dann sollte eine BROKEN auch irgendwie angeboten werden können.

**Comment by oszilloskop** [comment]
@ctr49 Du kannst uns ja mal auf dem Laufenden halten, ob es mit dem Banana Pro bei Dir  funktioniert.
Ich mach den Issue hier aber vorläufig zu.

**Comment by oszilloskop** [comment]
@ctr49 Könntest Du evtl. mal mittels https://dl.ffm.freifunk.net/firmware/dev/ nachschauen, ob das Frankfurter DEV BROKEN Banana Pro Image bei Dir wie gewünscht funktioniert?

**Comment by christf** [comment]
@oszilloskop  was genau ist am jenkins bei uns im Moment kaputt?

**Comment by oszilloskop** [comment]
@christf Der Build bricht aus mir unerklärlichen Günden ab.
Z.Z. versuche ich die DEV (Gluon 2016.2.1) mit dem neuen FirmwareBuilder zu bauen. Das klappt auchgut auf mehreren unterschiedlichen Maschinen, nur nicht mit unserem Jenkins.
Die aktuelle Fehlermeldung kannst Du (noch) hier sehen: http://jenkins.ffm.freifunk.net/jenkins/job/ffm_gluon-dev/222/console
P.S. Es wurde wegen des Fehlers mit "-j1 V=s" gebaut.

**Comment by oszilloskop** [comment]
Zur Zeit ist die Dev mit gesetztem "Broken" gebaut. 
Wenn es eine neue Stable geben sollte, dann werden wir irgendwie noch einen neuen Broken-Branch mit der Stable-Funktionalität erstellen.
Daher schliess ich das hier mal.

Wie @christf so schon sagt: Immer nur ein Thema pro Issue :o)

**Comment by ctr49** [comment]
@oszilloskop, entschuldige die späte Rückmeldung! Das ist irgendwie an mir vorbei gegangen.
Die Version ist inzwischen verschwunden, gäbe es die Möglichkeit, dass nochmal testweise anzuschalten?

**Comment by oszilloskop** [comment]
Zur Zeit bauen wir die Dev-Firmware nur sporadisch und dann ohne BROKEN (das spart enorm Zeit).
Werde mal die Tage einen Build der Dev mit BROKEN=1 anwerfen und dann auf den DL-Server packen.

**Comment by ctr49** [comment]
Habe gerade mal ein paar neuere Images ausprobiert, alles was auf CC basiert geht nicht. Also verschieben wir das mal bis Dev auf Gluon 2017 (LEDE) angekommen ist, dann funktioniert nämlich auch das eth Interface ohne Probleme (dwmac anstatt stmmaceth im neuen Kernel)!

**Comment by oszilloskop** [comment]
@ctr49 
Hm, schade. 

Trotz alledem liegt jetzt eine Dev-Firmware mit BROKEN-Ubterstützung auf dem DL-Server.
Hier schonmal für Banana PIs vorselektiert: 
https://ffm.freifunk.net/firmware/?q=Banana

**Comment by oszilloskop** [comment]
@christf 
Die Babel-Firmware basiert doch auf LEDE.
Baust Du die manchmal mit BROKEN=1 ?

Evtl. kann @ctr49 da ja etwas mit rumspielen.

**Comment by christf** [comment]
ja, auf Anfrage bau ich da mit BROKEN=1

On Fri, Aug 04, 2017 at 10:26:00AM -0700, oszilloskop wrote:
>@christf
>Die Babel-Firmware basiert doch auf LEDE.
>Baust Du die manchmal mit BROKEN=1 ?
>
>Evtl. kann @ctr49 da ja etwas mit rumspielen.
-- 
()  ascii ribbon campaign - against html e-mail
/\  against proprietary attachments

**Comment by ctr49** [comment]
Das wäre super, ein Vanilla LEDE 2017.1.x läuft schon sehr gut!
Hatte auch gerade mal probiert ein Gluon 2017.1.1 mit sife-ffffm zu kompilieren, aber scheitere an der neuen site.conf Syntax... gibt es da schon eine funktionierende config? (OT: hat schonmal jemand versucht die durch jsonlint zu jagen? da sind einige Kommata zu viel!)

**Comment by oszilloskop** [comment]
Nachdem unsere neue Stable hoffentlich Mitte/Ende August ausgerollt ist, werde ich mich mal mit Gluon 2017.1.x auseinandersetzen. Ist ja nicht nur die site.conf, auch die Packages müssen angepasst werden.

**Comment by christf** [comment]
Die nächste Babel Firmware in Version 0.0.1.8 wird mit Broken gerade gebaut, morgen sehen wir, was geklappt hat.
