### ISSUE TITLE
DNS Inbound forward block

### ISSUE THREAD

**Issue by skorpy2009** [freifunk-ffm/ToDo-Liste#23]
Block IPv6 DNS inbound (from Internet) in forwarding firewall

**Comment by christf** [comment]
warum hat das ein babel label?

**Comment by christf** [comment]
wo genau soll das geblockt werden?

**Comment by christf** [comment]
@skorpy2009 bitte hilf mir dabei dieses issue zu verstehen.

**Comment by christf** [comment]
Geht es wirklich nur um dns oder müssten wir nicht eine Firewall bauen die alles abdeckt

**Comment by skorpy2009** [comment]
@christf du hattest mir gesagt ich soll das hier reinschreiben, keine Aktivität => close
