### ISSUE TITLE
Map-Server: Wegen Kammeffekt einmal bitte den UDP-Buffer vergrößern

### ISSUE THREAD

**Issue by oszilloskop** [freifunk-ffm/ToDo-Liste#24]
Um den Kammeffekt der Map-Server-Graphen zu verringern, hilft evtl. ein vergrößern des UDP-Package-Buffers.

Laut @skorpy2009 in sysctl folgendes anpassen:
net.core.*mem_* 83886080 Byte

**Comment by christf** [comment]
reicht nicht. wir brauchen (siehe puppet)
       'set net.core.rmem_max 83886080',
       'set net.core.wmem_max 83886080',
       'set net.core.rmem_default 83886080',
       'set net.core.wmem_default 83886080',

**Comment by skorpy2009** [comment]
@christf mach ich und das sollte eigentlich eine passende regex werden, jdm war aber übereifrig

**Comment by Adorfer** [comment]
Macht ihr das zentral über Ansible&Puppet oder soll ich das lokal in die Config schreiben?

**Comment by skorpy2009** [comment]
@Adorfer leider ist dieser Map Server nicht im Puppet. Deswegen habe ich das schon Manuel gemacht.

**Comment by skorpy2009** [comment]
Die Droprate war aber bisher nicht hoch, so 1 Packet ca.

Mal schauen ob es vielleicht nicht einfach der Wumms ist...

**Comment by Adorfer** [comment]
Und, hat es geholfen?

**Comment by skorpy2009** [comment]
Bisher leider nicht merklich; Ich denke das das Hauptproblem die absolute Überlastung der Büchse ist.

**Comment by christf** [comment]
> >Und, hat es geholfen?
>nein
Also ziehen wir um und beenden nun dieses Dilemma?

-- 
()  ascii ribbon campaign - against html e-mail
/\  against proprietary attachments

**Comment by Adorfer** [comment]
Scorpy hat mit dem Aufsetzen der neuen VM (auf dags1) begonnen heute.
