### ISSUE TITLE
MailMan aufsetzen

### ISSUE THREAD

**Issue by skorpy2009** [freifunk-ffm/ToDo-Liste#25]
Vielleicht auf dem Uber?
Ziel:
Mailinglisten mit Archiv für $Dinge wie Technik etc.

user@ intern@ bleiben der redundanz erstmal bei Uberspace.

**Comment by oszilloskop** [comment]
Wenn der Archiver **Hyperkitty** nicht schon irgendwie bei Mailman v3.x dabei ist, könnte ich mich um den Archiver kümmern.
https://wiki.list.org/HyperKitty

**Comment by skorpy2009** [comment]
Man könnte dann auch Listen wie Richtfunk, Babel etc. machen.

**Comment by christf** [comment]
ich schau mir das mal an. Das wird auf der mail lxc vom uber am Ende laufen.

**Comment by christf** [comment]
die kontaktadresse von lists.freifunk.net hatte ich angeschrieben, bisher liegt keine Antwort vor. Wenn sich das in den nächsten 7 Tagen nicht ändert, setze ich mailman2 auf unserem mailserver auf. Hyperkitty-Anbindung müssen wir dann anderweitig klären.

**Comment by skorpy2009** [comment]
Wenn wir das schon selber machen, dann bitte nur mit mailman 3.

**Comment by christf** [comment]
>Wenn wir das schon selber machen, dann bitte nur mit mailman 3.
In welchem debian repository liegt der?

**Comment by t-8ch** [comment]
@christf 
https://freifunk.net/kontakt/issuetracker/ ("Anfrage Mailingliste")

**Comment by christf** [comment]
interessant, ich hatte die Kontaktadresse auf http://lists.freifunk.net/mailman/listinfo genutzt. Im Formular hab ich mich auch mal gemeldet.

Auch spannend: da gibts auch wordpress-instanzen.

**Comment by christf** [comment]
Kontakt ist hergestellt.

**Comment by christf** [comment]
erstellung von enigen ML ist angefragt. :)

**Comment by christf** [comment]
Eine Vorstand und admin Liste wurde heute erzeugt

**Comment by christf** [comment]
ML für admin und Vorstand sind erzeugt => Schließung.

**Comment by oszilloskop** [comment]
Wie lautet denn die Mailadresse der Admin-Liste?

**Comment by skorpy2009** [comment]
Leider scheint die aktuelle admin@ffm Probleme zu haben:

http://lists.freifunk.net/mailman/listinfo/admin-ffm-freifunk.net

**Comment by christf** [comment]
On Thu, Feb 02, 2017 at 06:58:58AM -0800, skorpy2009 wrote:
>Leider scheint die aktuelle admin@ffm Probleme zu haben:
>
>http://lists.freifunk.net/mailman/listinfo/admin-ffm-freifunk.net
Woran machst Du das fest? Das sieht für mich gnaz normal aus...

viele Grüße

Christof

>
>—
>You are receiving this because you modified the open/close state.
>Reply to this email directly, view it on GitHub, or mute the thread.*
>

-- 
()  ascii ribbon campaign - against html e-mail
/\  against proprietary attachments

**Comment by skorpy2009** [comment]
>Woran machst Du das fest? Das sieht für mich gnaz normal aus... 
Weil wir nicht meine Mail empfangen haben...

**Comment by christf** [comment]
On Thu, Feb 02, 2017 at 07:15:37AM -0800, skorpy2009 wrote:
>    Woran machst Du das fest? Das sieht für mich gnaz normal aus...
>    Weil wir nicht meine Mail empfangen haben...
Ich habe sie empfangen.

-- 
()  ascii ribbon campaign - against html e-mail
/\  against proprietary attachments

**Comment by skorpy2009** [comment]
Die hier:?

**Comment by christf** [comment]
=> die mailingliste läuft. wenn andere verteiler nicht gehen, dann braucht es ein anderes ticket.
