### ISSUE TITLE
prometheus-node-exporter fastd3 socket v4

### ISSUE THREAD

**Issue by skorpy2009** [freifunk-ffm/ToDo-Liste#26]
On the fastd3, prometheus-node-exporter only creates a IPv6 Socket, IPv4 currently still needed.

@t-8ch an idea? I couldn't find any config for this behavior.

**Comment by t-8ch** [comment]
The `batbridge` interface was down.
Somehow the systemd-networkd from jessie-backports thinks it is not configured correctly and does not bring it up

**Comment by skorpy2009** [comment]
Server neu aufgesetzt; Problem ist obsolut
