### ISSUE TITLE
uci commit in upgrade-scripts der ffffm paketen entfernen

### ISSUE THREAD

**Issue by christf** [freifunk-ffm/ToDo-Liste#27]
in den upgrade scripten wird ein bereits von gluon mitgebra htes 998-uci-commit-script ausgeführt.

das enlarge dns -cache-script sollte
a) vor diesem commit sctipt ausgeführt werdne, was durch umbenennen in 950-enlarge-dns-cache erreicht wird
b) selbst kein commit ausführen

folgende Pakete sind betroffen, in keinem sollte das upgrade-script ein commit ausführen.
- [ ] ffffm-enlarge-dns-cache
- [x] ffffm-fastd-auto-mtu
- [x] ffffm-autoupdater-use-site-conf-branch
- [ ] ffffm-keep-radio-channel

**Comment by oszilloskop** [comment]
Die Skripte sollten anstelle von uci:commit ein uci:save verwenden. Dieses ist die Vorstufe eines Commits in den Flash-Speicher.
Ein finaler Commit wird nach einem Upgrade dann durch das Gluon-Skript "[998-uci-commit-script](https://github.com/freifunk-gluon/gluon/blob/master/package/gluon-core/files/lib/gluon/upgrade/998-commit)" aus dem Package "Gluon-Core" erledigt.

**Comment by oszilloskop** [comment]
- Anpassungen in "ffffm-enlarge-dns-cache" nicht mehr möglich. Das Package wurde komplett umgestellt.
- Anpasungen in "ffffm-fastd-auto-mtu" durchgeführt.
- Anpassungen in "ffffm-keep-radio-channel" nicht möglich. Dort werden direkt Dateien geschrieben/angelegt.
-  Anpassungen in "ffffm-autoupdater-use-site-conf-branch" durchgeführt.
