### ISSUE TITLE
ffffm-fastd-auto-mtu sollte nicht im flash herumschreiben

### ISSUE THREAD

**Issue by christf** [freifunk-ffm/ToDo-Liste#29]
das paket ändert die mtu im flash. Das sollte es nicht tun

**Comment by oszilloskop** [comment]
Das Package macht dieses nur, wenn sich die MTU ändert, und das ist in der Regel sehr sehr selten.

**Comment by christf** [comment]
Fastd batch das in UCI.  Man kann das zwar neu jedem Boot bestimmen und im RAM halten aber muss dafür gluon-mesh-vpn-fastd umbauen. Das ist blöder als der commit.
