### ISSUE TITLE
Einen schönen Firmwareselektor erstellen

### ISSUE THREAD

**Issue by oszilloskop** [freifunk-ffm/ToDo-Liste#3]
Gewünschte Vorgaben:
- [x] Sollte nicht auf dem gleichen Server laufen müssen, auf dem auch die Firmware zum Download bereit liegt  
- [x] Design wie Frankfurter Webseite  
- [ ] Layout vertikal 
- [x] Einbindung in Wordpress wäre toll  
- [ ] Und das ganze irgendwie konfigurierbar machen (Hinweisstexte, Server-Pfade, css, etc.)
- [ ] Bestimmung aller Auswahlmöglichkeiten zur Laufzeit in Abhängigkeit der wirklich angebotenen Firmware-Dateien  
  - [x] Auswahl Hersteller  
  - [x] Auswahl Routername  (ggf. Herstellerbezeichnung entfernen)
  - [x] Auswahl Hardwarerevision (falls mehrere vorhanden, ältestes anzeigen)  
  - [ ] Auswahl Branch (wenn möglich stable als default)  
  - [x] Auswahl Factory / Sysupgrade
  - [ ] Die Auswahlstruktur so aufbauen, das weitere Auswahlmöglichkeiten leicht hinzufügbar sind (z.B. Batman/Babel, Fastd/L2TP, Frankfurt/Umland, Subdomain oder ähnliches)
- [ ] Anzeige Routergrafik Vorder-/Hinterseite anzeigen sobald Hersteller und Modell ausgewählt wurden. Router-Grafiken gibt es hier https://github.com/Moorviper/Freifunk-Router-Anleitungen/wiki
- [ ] Download Button (nur aktiv, wenn eine Firmware ausgewählt wurde)  
- [ ] Routernamen-Aliases ermöglichen (wegen Router Falschbenennungen)

**Beispiel:**  

![Design](https://raw.githubusercontent.com/oszilloskop/DiesUndDas/master/images/fw-downloader-design-01.png)

**Comment by Adorfer** [comment]
Wenn das Ding mit eine Config file (egal welche syntax) konfiguriert werden könnte, sich evtl auch Daten aus der Directory-Struktur und darin liegenden site. conf-Datein ziehen koennte, dann wäre das ein Projekt, das vermutlich vielen Communites helfen würde.

**Comment by MyIgel** [comment]
Genau das ist der Plan, er braucht dann nur eine Struktur wie [branch]/[type]/[firmwarefiles] & holt sich dort die Liste ab

**Comment by MyIgel** [comment]
* Liste aus Apache Dir List extrahieren / Manifest?
* Liste beim Bauen erzeugen
* Api-Endpoint zum abarbeiten

**Comment by MyIgel** [comment]
Aktueller Zwischenstatus der Implementierung (nach einigen fiesen regexen): Ich habe eine Liste mit Firmware Files und weiteren Metadaten (ein kleiner Ausschnitt):

```JSON
{
    "...": {},
    "netgear": {},
    "onion": {},
    "openmesh": {},
    "raspberry": {},
    "tp-link": {
        "...": {},
        "tl-wr710n": {},
        "tl-wr740n-nd": {},
        "tl-wr741n-nd": {},
        "tl-wr743n-nd": {},
        "tl-wr841n-nd": {
            "stable": {
                "factory": [
                    {
                        "...": "..."
                    },
                    {
                        "file": "gluon-ffffm-v2.0-stable-34-tp-link-tl-wr841n-nd-v10.bin",
                        "url": "https://dl.ffm.freifunk.net/firmware/stable/factory/gluon-ffffm-v2.0-stable-34-tp-link-tl-wr841n-nd-v10.bin",
                        "name": "tl-wr841n-nd",
                        "community": "ffffm",
                        "type": "bin",
                        "version": "v2.0-34",
                        "supplier": "tp-link",
                        "revision": "v10"
                    },
                    {
                        "file": "gluon-ffffm-v2.0-stable-34-tp-link-tl-wr841n-nd-v11.bin",
                        "url": "https://dl.ffm.freifunk.net/firmware/stable/factory/gluon-ffffm-v2.0-stable-34-tp-link-tl-wr841n-nd-v11.bin",
                        "name": "tl-wr841n-nd",
                        "community": "ffffm",
                        "type": "bin",
                        "version": "v2.0-34",
                        "supplier": "tp-link",
                        "revision": "v11"
                    }
                ],
                "sysupgrade": []
            },
            "test": {},
            "dev": {}
        },
        "tl-wr842n-nd": {},
        "tl-wr843n-nd": {},
        "tl-wr940n-nd": {},
        "tl-wr941n-nd": {}
    },
    "ubiquiti": {},
    "....": {}
}
```

**Comment by oszilloskop** [comment]
Goil!
Schön wäre noch, wenn unter "version" die volle Versionsbezeichnung, hier im Falle der Stable also   "v2.0-**stable**-34", stehen würde.

**Comment by oszilloskop** [comment]
Es wird jetzt der Firmware-Wizard aus Darmstadt verwendet: 
https://github.com/freifunk-darmstadt/gluon-firmware-wizard

Der Firmware-Wizard ist lokalisiert für Frankfurt.
Siehe https://ffm.freifunk.net/firmware/ 

Anpassungen des Wizard-Layout sollten noch stattfinden.
