### ISSUE TITLE
FFM-Repos auf Gluon 2016.2.1 aktualisieren

### ISSUE THREAD

**Issue by oszilloskop** [freifunk-ffm/ToDo-Liste#30]
FFM-Repos (dev, test, stable) auf Gluon 2016.2.1 aktualisieren.

Werde ich wohl beim nächsten Basteltreffen machen.

**Comment by oszilloskop** [comment]
- [x] dev
- [ ] test
- [ ] stable

**Comment by christf** [comment]
Babel ist auch schon auf dem Stand. Allerdings aus dem Master. 

Am 9. November 2016 01:16:43 MEZ, schrieb oszilloskop <notifications@github.com>:
>FFM-Repos (dev, test, stable) auf Gluon 2016.2.1 aktualisieren.
>
>Werde ich wohl bei nächsten Basteltreffen machen.

Viele Grüße

Christof
-- 
Diese Nachricht wurde mit K-9 Mail gesendet.

**Comment by oszilloskop** [comment]
Done
