### ISSUE TITLE
Teilnahme an der Thomas-Krenn-OSS Challenge

### ISSUE THREAD

**Issue by Adorfer** [freifunk-ffm/ToDo-Liste#31]
Laut 
https://www.thomas-krenn.com/de/unternehmen/kampagnen/thomas-krenn-award.html
gibt es Serverhardware-Gutscheine von insegesamt 6k€ zu gewinnen. 

Vielleicht was für die Babel-Entwicklung....

**Comment by christf** [comment]
ich bin mir nicht sicher. bislang ist das ja nur ein mini-PR für das gluon-projekt und kein eigenes Open Source Projekt.

**Comment by skorpy2009** [comment]
Einreichung gerade bestätigt bekommen

**Comment by skorpy2009** [comment]
So, wer fährt zu den CLTs und vertritt uns bei der Übergabe der Gewinnes zum  3. Platz: Hardware im Wert von 1.500 € ?

**Comment by oszilloskop** [comment]
Und? Wie sieht es aus?

**Comment by skorpy2009** [comment]
So: https://chaospad.de/p/WkfOokrWGd

**Comment by MyIgel** [comment]
Make Blogeintrag's great again! :tada:

**Comment by christf** [comment]
auf das chaospad komm ich nicht.

**Comment by oszilloskop** [comment]
ich auch nicht

**Comment by oszilloskop** [comment]
So, wir haben den 3.ten gemacht -> https://ffm.freifunk.net/2017/03/22/babel-l3roamd-gluon-intergations-projekt-gewinnt-den-3-platz-beim-thomas-krenn-award-2017/

Daher Close.
Bei Bedarf einfach wieder öffnen.
