### ISSUE TITLE
Wochentag Basteltreffen

### ISSUE THREAD

**Issue by skorpy2009** [freifunk-ffm/ToDo-Liste#32]
Anscheinend ist der Mittwoch unpassend und wir müssen sowieso beim CCC "verlängern".

Der Dienstag und Donnerstag entfallen als Möglichkeit im CCC und auch bei mehreren privat.

Ich schlage den 2 oder 3 Montag im Monat vor.

Nachdem wir dies Diskutiert haben, werde ich das ganze auf die user@ Liste nochmal "anmerken"....

**Comment by christf** [comment]
Ich finde montage toll.

-- 
()  ascii ribbon campaign - against html e-mail
/\  against proprietary attachments

**Comment by t-8ch** [comment]
Bin auch für Montag

**Comment by MyIgel** [comment]
Montag passt, frei ist es im CCC auch -> gibt keine Unterkunfts-Treffen mehr

**Comment by Adorfer** [comment]
3. Montag im Monat vielleicht?

**Comment by skorpy2009** [comment]
1. Montag ist "Freifunker Treffen"
3. Montag: Basteltreff?
alle "paar" Monate Montags Vorstandstreffen
anderer Montag Möglichkeit für Arbeitstreffen

**Comment by oszilloskop** [comment]
https://www.youtube.com/watch?v=h81Ojd3d2rY

**Comment by christf** [comment]
Gern. Vorstandstreffen finden dann wohl an 2. Montag von geraden Monaten statt. 

Wie passt denn der 3. Montag im Monat dem Jason zum basteln? 

Am 9. November 2016 22:46:21 MEZ, schrieb skorpy2009 <notifications@github.com>:
>1. Montag ist "Freifunker Treffen"
>3. Montag: Basteltreff?
>alle "paar" Monate Montags Vorstandstreffen
>anderer Montag Möglichkeit für Arbeitstreffen

Viele Grüße

Christof
-- 
Diese Nachricht wurde mit K-9 Mail gesendet.

**Comment by ipsecguy** [comment]
Montag is cool.

**Comment by oszilloskop** [comment]
@christf Der 3. Montag wäre dann aber direkt der Tag nach dem Sonntagstreffen. Das ist nicht so toll.
Ich schlage den 2. Montag im Monat vor. Das ist einfach zu merken.
Es ist dann **immer** der folgende Montag nach dem regelmäßigem Treffen im Depot.

**Comment by christf** [comment]
Genau das finde ich aber nicht ideal, weil das immer zwei Wochen in Folge blockiert

**Comment by oszilloskop** [comment]
Der 3. Montag würde aber bei einigen zwei Tage in Folge blockieren.

**Comment by oszilloskop** [comment]
Lass uns alle würfeln :o)

**Comment by Adorfer** [comment]
Dann den 4. Montag des Monats?

**Comment by christf** [comment]
@oszilloskop  das hatte ich übersehen - dan nbleiben wir dabei
1. Montag - offenes Treffen
2. Montag - Basteltreffen
3. 2-wöchig versetzt zum 1. Montag an einem Sonntag - offenes Treffen

ok?

**Comment by oszilloskop** [comment]
@christf 
Von meiner Seite aus ja, aber ich bin ja nur ein halber Bastler :o)

**Comment by MyIgel** [comment]
Der 2. Montag im Monat fürs Basteltreffen traf auf keine Einwände im Plenum

@skorpy2009 & @MyIgel passen auf

**Comment by skorpy2009** [comment]
Unsere Treffen heißen "offenes Freifunker Treffen" und ? Wollen wir vielleicht was anderes als Basteltreffen nehmen bevor ich das auf die user@ kippe

**Comment by oszilloskop** [comment]
Man könnte sich an dem Beschreibungstext des bisherigem Basteltreffen orientieren (siehe https://ffm.freifunk.net/Veranstaltung/basteln-fuer-freifunk/?instance_id=686 ). Und sich dann sowas wie "Arbeitstreffen" o.ä. ausdenken.

**Comment by skorpy2009** [comment]
Öffentliche Termine 2017:
1. Montag: Offenes Freifunker Treffen
2. Montag: Technik-/Arbeitstreffen
3. Sonntag (oder den zweiten darauf folgenden Sonntag?) : Offenes Freifunker Treffen

**Comment by christf** [comment]
bitte ein issue pro Thema. Die Benamsung ist was Neues. 

Technik-Arbeitstreffen gefällt mir nicht so gut, weil das so nach Arbeit klingt. Ich find Basteltreffen eigentlich ganz gut, weil es so schön hemdsärmelig klingt.

und Offenes Freifunker Treffen <= da finde ich offenes Treffen besser. Es dürfen ja nicht nur Freifunker hin kommen.

**Comment by oszilloskop** [comment]
Zyklus-Konsens, 2. Montag im Monat und bereits beim CCC gebucht.
Geschlossen.
