### ISSUE TITLE
Generisches Puppet

### ISSUE THREAD

**Issue by MyIgel** [freifunk-ffm/ToDo-Liste#33]
* Fastd
* Monitoring
* nicht nur l2
* Batman/Babel? optional

- Teile des lxc recyceln?

**Comment by christf** [comment]
vielleicht wäre es gut, zunächst  Ziele festzulegen. Was soll erreicht werden? :)

**Comment by MyIgel** [comment]
Mittlerweile eher ein generisches salt ;)

**Comment by oszilloskop** [comment]
Gibt's was neues?

**Comment by skorpy2009** [comment]
Da alles aktuelle in Salt ist und da möglichst flexibel und generisch ist, können wir dieses Issue schließen?

**Comment by skorpy2009** [comment]
@oszilloskop bitte schließe keine Issues die du nicht selber aufgemacht hast / wo du eindeutig sagen kannst, das es behoben ist.
