### ISSUE TITLE
Workflow Puppet

### ISSUE THREAD

**Issue by skorpy2009** [freifunk-ffm/ToDo-Liste#34]
Ich würde es bevorzugen, wenn GitHub das Master Repo für das Puppet ist.
Aktuell ist das leider nicht der Fall, da eine Synchronizations anscheinend das Problem ist. @t-8ch @christf wollen wir dies über eine Webhook lösen, so das der Puppet Master immer getriggert wird wenn jemand etwas ins GitHub push. Das wäre auch nur eine One Way Lösung.

**Comment by t-8ch** [comment]
Das wird ultra schmerzhaft das zu bauen

**Comment by skorpy2009** [comment]
Ach was, eine WebApp am besten in NodeJS und ein bissel PHP lösen das schon.

**Comment by skorpy2009** [comment]
https://github.com/crocket/gitlab-pull-webhook/blob/master/pull.js

oder mit folgendem Shell Anteil:
#!/bin/sh
cd $(dirname $0)
git -C supernode_puppet fetch
git -C supernode_puppet reset --hard origin/production -- //Naja, eigentlich will ich hier alle Repos ziehen und nicht nur production :(

**Comment by skorpy2009** [comment]
Mir ist Puppet jetzt egal.
