### ISSUE TITLE
FFFFM Kernel 4.9

### ISSUE THREAD

**Issue by skorpy2009** [freifunk-ffm/ToDo-Liste#35]
Auf dem fastd6 wird ein eigener Kernel mit legazy Batman getestet. Folgende Fehler wurden schon beobachtet:
root@fastd6:~# ip -6 rule add iif eth1 lookup ffffm
RTNETLINK answers: Address family not supported by protocol

root@fastd6:~# sysctl -p
kernel.panic = 1
kernel.panic_on_oops = 1
sysctl: cannot stat /proc/sys/kernel/softlockup_panic: Datei oder Verzeichnis nicht gefunden
net.nf_conntrack_max = 1337000
sysctl: cannot stat /proc/sys/net/ipv4/netfilter/ip_conntrack_max: Datei oder Verzeichnis nicht gefunden
sysctl: cannot stat /proc/sys/net/ipv4/netfilter/ip_conntrack_generic_timeout: Datei oder Verzeichnis nicht gefunden
sysctl: cannot stat /proc/sys/net/ipv4/netfilter/ip_conntrack_tcp_timeout_established: Datei oder Verzeichnis nicht gefunden

**Comment by skorpy2009** [comment]
Other Problems:
[backtrace.txt](https://github.com/freifunk-ffm/ToDo-Liste/files/658067/backtrace.txt)

**Comment by t-8ch** [comment]
`ip_conntrack_generic_timeout` und `ip_conntrack_tcp_timeout_established` auch nicht mehr. `ip_conntrack_max` is vll woanders.

**Comment by t-8ch** [comment]
Der backtrace liegt wahrscheinlich an unserem lock debugging. Der Fehler ist schon immer da. Könnte wohl an die batman entwickler weitergegeben werden

**Comment by t-8ch** [comment]
@skorpy2009 der neue Kernel liegt auf fastd6 und kann installiert und aktiviert werden

**Comment by skorpy2009** [comment]
Mit dem neuen Batman-adv-legacy Paket von Neoraider und einem sehr neuen 4.9er Kernel dreht das ganze :) (noch)
