### ISSUE TITLE
Die Funktionalität des WDS/Wifi-Tasters entfernen (Step #1)

### ISSUE THREAD

**Issue by oszilloskop** [freifunk-ffm/ToDo-Liste#38]
Dieser Issue hier wurde aufgesetzt, damit von mehreren Leuten mal Pro und Kontra ausgelotet werden können.

### Funktion:
Mit dem experimentellem Package [ffffm-button-bind](https://github.com/freifunk-ffm/packages/tree/master/ffffm-button-bind) kann der Wifi-Taster lahmgelegt werden.

### Hintergrund:
Es gibt Situationen, bei welchen manchmal versehentlich der unscheinbare WDS/Wifi-Taster eines FF-Routers gedrückt wird, insbesondere bei Router-Aufstellplätzen welche für unbedarfte FF-Nutzern zugänglich sind. Die FF-Nutzer wissen dann meist nicht warum das Netzt plötzlich nicht mehr funktioniert.

Je nach Befund könnte dieses Package in die nächste "Stable"-Firmware aufgenommen werden.

**Comment by Adorfer** [comment]
Dafür. 
Wer es wirklich abstellen will: Shell benutzten oder Setup-Mode.

**Comment by oszilloskop** [comment]
So, es ist jetzt ein neues Packages entstanden -> [ffffm-button-bind](https://github.com/freifunk-ffm/packages/tree/master/ffffm-button-bind)
