### ISSUE TITLE
Autoupdate Verhalten "verbessern"

### ISSUE THREAD

**Issue by skorpy2009** [freifunk-ffm/ToDo-Liste#39]
Gluons Autoupdate Verhalten ist nun von der "priority" in der "manifest" Datei abhängig.
Vorschlag für die Dev:
Siehe site-ffffm PR 12: https://github.com/freifunk-ffm/site-ffffm/pull/12
Siehe site-ffffm PR 13: https://github.com/freifunk-ffm/site-ffffm/pull/13

**Comment by oszilloskop** [comment]
Siehe auch Gluon Doc: http://gluon.readthedocs.io/en/latest/features/autoupdater.html#building-images

**Comment by oszilloskop** [comment]
Dev ist fertig

**Comment by oszilloskop** [comment]
Test und Stable sind ebenfalls angepasst.
