### ISSUE TITLE
Fördermitgliedschafts Werbe Wordpress Seite fertigstellen

### ISSUE THREAD

**Issue by skorpy2009** [freifunk-ffm/ToDo-Liste#41]
Die Fördermitgliedsschafts Werbe Seite schön machen für Werbung und so.

Ziel => mehr Fördermitglieder => mehr Geld

**Comment by oszilloskop** [comment]
Brauchen wir noch eine weitere Fördermitglied-Werbeseite, oder reicht die Spendenseite aus?

Hier die Spendenseite: https://ffm.freifunk.net/spenden/

Falls die Spendenseite ausreicht, dann diesen Punkt bitte schliessen.

**Comment by christf** [comment]
Ich halte die bestehende Seite für gut. Verbesserungsvorschläge können in einem separaten Ticket geführt werden.
