### ISSUE TITLE
Umzug der Jobs von jenkins auf jenkins2

### ISSUE THREAD

**Issue by christf** [freifunk-ffm/ToDo-Liste#43]
der jenkins soll bald abgeschaltet werden. Nach dem Umzug wird der CNAME geändert sodass jenkins2 dann unter jenkins.ffm.freifunk.net erreichbar sein wird.

**Comment by oszilloskop** [comment]
@christf 
Habe es gerade mal getestet.  jenkins.ffm.freifunk.net ist nicht erreichbar.
Kann das hier geschlossen werden?
