### ISSUE TITLE
SSH Keys aufräumen

### ISSUE THREAD

**Issue by skorpy2009** [freifunk-ffm/ToDo-Liste#46]
Wir MÜSSEN uns Gedanken machen die SSH Keys auf den Servern aufzuräumen um 1. Ordnung rein zu bringen und um ein wenig mehr Sicherheit zu gewähren.

**Comment by skorpy2009** [comment]
sudo / admin Rechte brauche aktuell denke ich nur:
- @christf 
- @t-8ch 
- @MyIgel 
- me

Auf den jeweiligen weiteren Kisten kann man extra User anlegen falls da jemand drauf muss ( Betreiber... )

**Comment by MyIgel** [comment]
Sehe ich genauso

**Comment by christf** [comment]
Ack. 
Viele Grüße

Christof
-- 
Diese Nachricht wurde mit K-9 Mail gesendet.

Am 14. Mai 2017 13:45:01 MESZ schrieb skorpy2009 <notifications@github.com>:
>sudo / admin Rechte brauche aktuell denke ich nur:
>- @christf 
>- @t-8ch 
>- @MyIgel 
>- me
>
>Auf den jeweiligen weiteren Kisten kann man extra User anlegen falls da
>jemand drauf muss ( Betreiber... )

**Comment by skorpy2009** [comment]
erledigt
