### ISSUE TITLE
ToDo's wenn der OVH Map Server irgendwann™ nicht mehr benötigt wird

### ISSUE THREAD

**Issue by MyIgel** [freifunk-ffm/ToDo-Liste#47]
@skorpy2009 das root passwort schicken -> macht alles kapott

* VMs hdd mit /dev/zero überschreiben
* Salt Secrets rausschmeißen
* LetsEncrypt revoken
* DD der kompletten festplatte

More to come...

**Comment by christf** [comment]
hier wäre noch cool wie man die schrite macht. das erste und vierte bekomme ich hin, bei den anderen wirds schwer...

**Comment by skorpy2009** [comment]
2. salt-key -d "$HOSTNAME"

**Comment by oszilloskop** [comment]
Wird der OVH Map Server noch benötigt?

**Comment by skorpy2009** [comment]
@oszilloskop wie meinst du das genau?

**Comment by oszilloskop** [comment]
@skorpy2009 
Das Issue lautet "ToDo's wenn der OVH Map Server irgendwann™ nicht mehr benötigt wird".
Meine Frage ist: "Nutzen/benötigen wir den OVH-Server noch?"

**Comment by skorpy2009** [comment]
JA!
Der gesammte Map Stack läuft noch darauf!

**Comment by Adorfer** [comment]
Was ist denn der "OVH Mapserver". IPv4 und/oder Mac vom primären eth würden helfen.

**Comment by skorpy2009** [comment]
erledigt am 27.09.

**Comment by Adorfer** [comment]
d.h. die VM mit der primären MAC 02:00:00:d7:c3:ba auf der OVH-Maschine kann weg?
Würde ich dann wie gefordert nächste woche aus /dev/zero überschreiben.

**Comment by skorpy2009** [comment]
Das hat nix mit dem kram der bei euch liegt zu tun

**Comment by Adorfer** [comment]
also OVH-VM mit der MAC 02:00:00:d7:c3:ba wieder anschalten?

**Comment by skorpy2009** [comment]
Ja. Wir hatten das schon mal. Das ist nicht die VM sondern der SERVER gewesen.

**Comment by Adorfer** [comment]
Auf dem Server liegt die VM. 
ich verstehe es so, dass wenn der der Mapserver nicht mehr auf dem Server liegt, dass dann auch die VM platt gemacht wird.
