### ISSUE TITLE
alles kaputt

### ISSUE THREAD

**Issue by skorpy2009** [freifunk-ffm/ToDo-Liste#49]
Jun  3 22:37:31 edge-fra-01 systemd[1]: Starting Load Kernel Modules...
Jun  3 22:37:31 edge-fra-01 systemd-modules-load[15280]: Failed to find module 'acpiphp'
Jun  3 22:37:31 edge-fra-01 systemd-modules-load[15280]: Failed to find module 'pci_hotplug'
Jun  3 22:37:31 edge-fra-01 systemd[1]: systemd-modules-load.service: Main process exited, code=exited, status=1/FAILURE
Jun  3 22:37:31 edge-fra-01 systemd[1]: Failed to start Load Kernel Modules.
Jun  3 22:37:31 edge-fra-01 systemd[1]: systemd-modules-load.service: Unit entered failed state.
Jun  3 22:37:31 edge-fra-01 systemd[1]: systemd-modules-load.service: Failed with result 'exit-code'.

**Comment by oszilloskop** [comment]
Close?
