### ISSUE TITLE
neue site.mk und site.conf für Gluon 2017

### ISSUE THREAD

**Issue by ctr49** [freifunk-ffm/ToDo-Liste#50]
Im Zuge von #21 habe ich mir selbst mal eine Firmware basierend auf Gluon 2017.1.1 und der site-ffffm gebaut. Da sich einiges an der site.conf und site.mk geändert hat, wollte ich hier mal meinen Stand dokumentieren. Als Pull-Request macht es derzeit ja keinen Sinn, sondern erst wenn dev auch auf Gluon 2017.x ist.
ffm-autokey habe ich in der site.mk rausgenommen, konnte nicht finden, wo das hinzeigt. Ansonsten baut Gluon mit den beiden Dateien sauber durch und (ohne weitere Änderungen) bootet es auch auf meinem BananaPi Pro, zwei TP-Links werde ich noch testen. Die br-setup wird ebenfalls gebildet und die normale Setup-Seite auf 192.168.1.1 präsentiert, weiter habe ich noch nicht getestet (da ich noch Probleme mit dem ap6210/brcmfmac auf dem Banana habe). Sie basiert auf den site-ffffm Dateien mit den Änderungen aus dem changelog bzw der example-site.

site.mk.diff
```
--- site.mk	2017-08-06 12:24:59.000000000 +0200
+++ site.mk.2017	2017-08-06 12:30:20.000000000 +0200
@@ -1,24 +1,37 @@
 GLUON_SITE_PACKAGES := \
         gluon-alfred \
+        gluon-respondd \
         gluon-autoupdater \
-        gluon-config-mode \
+        gluon-config-mode-autoupdater \
+        gluon-config-mode-contact-info \
+        gluon-config-mode-core \
+        gluon-config-mode-geo-location \
+        gluon-config-mode-hostname \
+        gluon-config-mode-mesh-vpn \
         gluon-ebtables-filter-multicast \
         gluon-ebtables-filter-ra-dhcp \
-        gluon-legacy \
-        gluon-luci-admin \
-        gluon-luci-autoupdater \
-        gluon-next-node \
-        gluon-mesh-batman-adv \
+        gluon-web-admin \
+        gluon-web-autoupdater \
+        gluon-web-network \
+        gluon-web-wifi-config \
+        gluon-mesh-batman-adv-15 \
         gluon-mesh-vpn-fastd \
         gluon-ffmautokey \
         gluon-radvd \
+        gluon-setup-mode \
         gluon-status-page \
-        iwinfo \
+        haveged \
         iptables \
-        haveged
+        iwinfo
 
 
-DEFAULT_GLUON_RELEASE := 0.4.1+0-exp$(shell date '+%Y%m%d')
+DEFAULT_GLUON_RELEASE := 0.6+exp$(shell date '+%Y%m%d')
 
 # Allow overriding the release number from the command line
 GLUON_RELEASE ?= $(DEFAULT_GLUON_RELEASE)
+
+GLUON_PRIORITY ?= 0
+
+GLUON_REGION ?= eu
+
+GLUON_LANGS ?= en de
```

site.conf.diff
```
--- site.conf	2017-08-06 12:24:31.000000000 +0200
+++ site.conf.2017	2017-08-06 12:34:17.000000000 +0200
@@ -34,10 +34,14 @@
                 mac = '16:41:95:40:f7:dc',
         },
 
-        fastd_mesh_vpn = {
-                methods = {'salsa2012+gmac'},
+        mesh_vpn = {
                 mtu = 1426,
-                backbone = {
+                fastd = {
+                    methods = {'salsa2012+gmac'},
+                    enabled = true,
+                    configurable = true,
+                    groups = {
+                      backbone = {
                         limit = 2,
                         peers = {
                         fastd1 = {
@@ -93,9 +97,10 @@
                         key = '55d23f51067cf83967b991cf06fee710d59b0c26d184529eb319405a5e37782e',
                         remotes = {'ipv4 "fastd8.ffm.freifunk.net" port 10000'},
                       }
-                        
-                        },
-                },
+                      }
+                   }
+                   }
+                }
         },
 
         autoupdater = {
```

**Comment by oszilloskop** [comment]
Danke.
Wir sind ja gerade dabei ein neu Stable auszurollen. Wenn wir das durch haben (in 1 bis 2 Wochen), dann werden wir mit der Migration von Gluon 2017.x anfangen. Dann wird da demnächst auch eine Dev-FW rausfallen.

**Comment by christf** [comment]
was machen wir damit? Aktuell ist unser dev-stand fürd en gluon-master baufähig.

**Comment by ctr49** [comment]
Da waren keine nennenswerten Änderungen von mir drin, ich wollte nur den Weg auf Gluon 2017.x beschleunigen und meine dafür nötigen Anpassungen teilen (wobei das nur für vanilla gluon war, nix für ffffm)

**Comment by christf** [comment]
das hat geklappt. :)  Ist damit das Ziel dieses issues erreicht?

**Comment by oszilloskop** [comment]
site.conf und site.mk wurden angepasst und bereits in der LEDE-basierenden Test-FW v2.4.2-test-0127 realisiert.

Test site.conf: https://github.com/freifunk-ffm/site-ffffm/blob/test/site.conf
Test site.mk: https://github.com/freifunk-ffm/site-ffffm/blob/test/site.mk
