### ISSUE TITLE
Wegfall von VM  5.196.175.55/02:00:00:d7:c3:ba zum 10.01.2018

### ISSUE THREAD

**Issue by Adorfer** [freifunk-ffm/ToDo-Liste#52]
Ankündigung: 
Die VM 02:00:00:d7:c3:ba wird zum 10.01.2018 ablaufen, da das komplette OVH-Blech bei ffdus wegfällt. 

Wo ist das Ding?
Auf Blech "twin1" 
 - RBX6 - Rack: 46C02 - Server-ID: 613070
 - 51.254.47.239  twin2.ffdus.de  001:41d0:1008:07ef::/64
 - account gs180732-ovh , "SP32@ovh" 
 -  83,29 € | 1M | 10.01.2018

Was auf der VM läuft? Keine Ahnung. 
begrüsst mich mit 
![grafik](https://user-images.githubusercontent.com/10302493/33522059-6aa41b68-d7e3-11e7-8fea-050a3d95dfde.png)

Tut das Ding derzeit was? Hat es einen "realen Namen": Keine Ahnung!
Vielleicht sagt das ja jemanden was von Euch: 
![grafik](https://user-images.githubusercontent.com/10302493/33522068-a6971468-d7e3-11e7-953b-39f248c1e5ca.png)

Bitte gebt Bescheid, wenn ihr das Image davon irgendwo "hinhaben" möchtet und/oder ob ich Euch ein Rescue-Medim einlegen soll, damit ihr das selbst per dd&co wegholen könnt.

**Comment by christf** [comment]
@skorpy2009 @MyIgel läuft da noch ein Dienst/Daten, der umgezogen werden muss?

**Comment by MyIgel** [comment]
Öh, wir haben da nen Blech? ;)

Mit welchen Zugangsdaten kommt man da drauf?

**Comment by Adorfer** [comment]
Mein Kenntnisstand ist obiger. 
Aber jedes Mal, wenn wir uns in der Vergangenheit drauf geeinigt hatten, das nicht mehr zu brauchen oder ich zumindest den Eindruck hatte und ich die VM abgeschaltet habe, meldete sich nach kurzer Zeit Leute, dass ich das bitte wieder anschalten solle. Ohne mir jedoch mitzuteilen, was das für ein Gerät ist und wie man diese zukünftig zur Vermeidung von Verwechslungen referenzieren könnte.

**Comment by MyIgel** [comment]
Dann schalte es jetzt aus -> wenn es gebraucht wird wird man es merken ;)

Ich weiß aktuell nicht wie ich auf die Kiste komme (kann also nicht nachschauen was drauf läuft) / Für was sie gedacht war / verwendet wird. Gibt es da irgendwo was?

**Comment by Adorfer** [comment]
Ist aus.

**Comment by MyIgel** [comment]
Ich habe gerade rausgefunden was das für ein Host ist: grafana.ffm.freifunk.net -> da läuft das Grafana für die Stats der Legacy iInfrastruktur drauf (Also alles was nicht über Salt aufgesetzt wurde).

Ich werde da mal eine Weiterleitung auf unser neues Grafana einbauen.

Wenn jemand also das alte Grafana vermisst sollte er sich melden //CC @christf @oszilloskop 

Eventuell könnte man noch mal die Daten von der Festplatte kratzen

**Comment by christf** [comment]
es hat sich keiner gemeldet der Termin ist vorbei.
