### ISSUE TITLE
Struktur von neighbours-babel anpassen, sodass sie auf die batman-Struktur passt

### ISSUE THREAD

**Issue by christf** [freifunk-ffm/ToDo-Liste#56]
damit hat es yanic leichter und kann die Strukturen direkt auslesen. Siehe auch
https://github.com/FreifunkBremen/yanic/pull/104

         18:13         genofire| kannst auch die struktur anpassen wie bei batman ala
         18:13         genofire| "2e:14:e7:d3:3a:90": {
         18:13         genofire| I"ifname": "vx_mesh_wan",
         18:13         genofire| I"neighbours":{
         18:13         genofire| II"02:f3:e2:f5:33:5c": {
         18:13         genofire| III "protocol": "babel",
         18:13         genofire| III "rxcost": 96,
         18:13         genofire| III "txcost": 96,
         18:13         genofire| III "cost": 96,
        18:13         genofire| III "reachability": 65535,
         18:13         genofire| III "address-ll": "fe80::f3:e2ff:fef5:335c",
         18:13         genofire| III "address-mesh": "fd2f:5119:f2d::f3:e2ff:fef5:335c"
         18:13         genofire| II}
         18:13         genofire| I}

**Comment by christf** [comment]
done.

**Comment by genofire** [comment]
## Current state of batman
#### of respondd "gluon-neighbour-info -r neighbours"
```js
{
  "batadv": {
    "e6:57:15:0e:f0:2c": {
      "neighbours": {
        "5e:f5:6c:df:75:94": {
          "tq": 255,
          "lastseen": 0.02
        },
        "d6:03:60:12:91:34": {
          "tq": 255,
          "lastseen": 2.89
        }
      }
    }
  },
  "wifi": {},
  "node_id": "18d6c790dd24"
}
```

#### of status-page "/cgi-bin/dyn/neighbours-batadv"
```
data: {"5e:f5:6c:df:75:94":{"tq":255,"lastseen":1.1000000000000001,"ifname":"br-mesh_lan"},"d6:03:60:12:91:34":{"tq":255,"lastseen":3.9199999999999999,"ifname":"br-mesh_lan"}}
```

**Comment by genofire** [comment]
current state:
```js
{
  "babel": {
    "mesh-vpn": {
      "protocol": "babel",
      "neighbours": {
        "fe80::98ae:57ff:fea7:594a": {
          "rxcost": 96,
          "txcost": 96,
          "cost": 96,
          "reachability": 65535
        }
      }
    },
    "vx_mesh_lan": {
      "protocol": "babel",
      "neighbours": {
        "fe80::2c14:e7ff:fed3:3a90": {
          "rxcost": 96,
          "txcost": 96,
          "cost": 96,
          "reachability": 65535
        }
      }
    }
  },
  "wifi": {},
  "node_id": "525400384b77"
}
```
i need the link-local of the current interface, too.
(in `nodeinfo` the current link-local is not listed and i would not know on which interface, which link-local is added)
