### ISSUE TITLE
uradvd: Erweiterung des Features: Announce MTU an clients.

### ISSUE THREAD

**Issue by christf** [freifunk-ffm/ToDo-Liste#58]
so lassen sich die Nebenwirkungen von MTU blackholes im Internet reduzieren. Siehe dazu #53

**Comment by ctr49** [comment]
Es kam das Argument, dass nicht alle clients die per RA ausgesandte MTU nutzen. Gibt es dazu irgendwelche Doku? Ich finde deutlich mehr stacks, die kein RDNSS verstehen.
Evtl. lässt sich beides per DHCPv6 erschlagen.

**Comment by christf** [comment]
Dhvpv6 wollen wir nicht einsetzen. Insofern ist schon aus Kompatibilitätsicht fraglich ob wir das wirklich bauen sollten. Der aktuelle clamping-Workaround funktioniert gut genug, denk ich.

**Comment by christf** [comment]
Schließung mit Verweis auf den workaround.
