### ISSUE TITLE
Xlat für das babel Netz bauen, damit ipv4 möglich wird

### ISSUE THREAD

**Issue by christf** [freifunk-ffm/ToDo-Liste#65]
Nicht alle Geräte können sich mit einem IPv6-only-Netz mit Nat64 verbinden.

- Android <5 können finden ohne IPv4-Adresse keine Netzwerkverbindung. https://www.statista.com/statistics/271774/share-of-android-platforms-on-mobile-devices-with-android-os/
- Windows 7 erhält keine Verbindung https://www.neowin.net/news/windows-7-loses-market-share-in-latest-reports
  
Wer kann zu den Systemen in unklarem Zustand sagen ob eine Verbindung möglich ist?

Systeme, die keine Verbindung erhalten. (hier steht der Marktanteil von Statistikseiten wie dieser: https://de.statista.com/statistik/daten/studie/157902/umfrage/marktanteil-der-genutzten-betriebssysteme-weltweit-seit-2009/):
- [ ] Android <=4 (20% der Android-Nutzer
- [ ] Windows 7 (35% der Desktop-Nutzer)
- [ ] Windows XP (4% der Desktop-Nutzer)
- [ ] Windows Vista (1% der Desktop Nutzer)
- [ ] Windows 8 (8% der Desktop-Nutzer) < geht prinzipiell wobei RDNSS nicht funktioniert.

Systeme, die eine Verbindung erhalten:
- [x] MacOS (10%)
- [x] Linux (2% )
- [x] iOS
- [x] Android >=5 (80% der Android-Nutzer)
- [x] Windows 10 (28% der Desktop-Nutzer)

**Comment by christf** [comment]
Der letzte Babel-snapshot (0.1.8-Snapshot53) verteilt IPv4-Adressen an Clients, die bezogen auf die MAC-Adresse statisch sind. Damit kann mein Android 4 bereits eine Verbindung ins Netz aufbauen. IPv4 selbst ist zwar kaputt, weil die xlat-Einstellungen am Node noch nicht korrekt sind, da die Kommunikation ins Netz jedoch per IPv6 und über xlat64 am Endpunkt des Netzes auch das IPv4-Interenet erreichbar ist, sind die Auswirkungen schonmal weniger dramatisch.

Alle Clients können sich jetzt verbinden, lediglich Programme, die IPv4-Adressen hart kodieren dürften nicht funktionieren. Daneben sind IPv4-Verbindungen jetzt ein bisschen langsamer als sie sein könnten weil zunächst die v4-Verbindung scheitern muss bevor die xlat-Technologie zum Einsatz kommen kann.

**Comment by christf** [comment]
ich ändere dann mal den Titel mit dem neuen Stand - für v4-Nutzer ist das Netz langsamer als es sein könnte.

**Comment by christf** [comment]
@codefetch ist da dran.

**Comment by christf** [comment]
Wir haben nun gluon-xlat46 in der Firmware, damit haben Clients natives IPv4

**Comment by rotanid** [comment]
> Wir haben nun gluon-xlat46 in der Firmware, damit haben Clients natives IPv4

can you link the repo of that package?

**Comment by christf** [comment]
I took the liberty of raising PR  for the package as https://github.com/freifunk-gluon/gluon/pull/1808
