### ISSUE TITLE
*.ffffm nach *.ffffm.net umziehen

### ISSUE THREAD

**Issue by MyIgel** [freifunk-ffm/ToDo-Liste#68]
Dadurch kann der DNS Server auf uber endlich abgeschaltet werden

**Comment by oszilloskop** [comment]
Es muss jedoch irgendwie sichergestellt sein, dass *.ffffm weiterhin aufgelöst wird.
Weil sonst werden sich die aktuell im Netz befindlichen Nodes (Stand 11.01.2018) nicht über 'updates.services.ffffm' updaten können. Selbst wenn sie es wollten oder sogar es sollten.

Edit: 
Das Problem etwas besser formuliert.
