### ISSUE TITLE
neue sysctl werte mergen

### ISSUE THREAD

**Issue by christf** [freifunk-ffm/ToDo-Liste#8]
nach review!

**Comment by christf** [comment]
@skorpy2009 wo hattest Du den Entwurf abgelegt?

**Comment by skorpy2009** [comment]
Branch sysctl?




Mit freundlichen Grüßen,

Magnus Frühling

-—-—-—-—-—-—-—-—-—-—-—-—-

Mobil gesendet...

**Comment by christf** [comment]
also dort: https://github.com/freifunk-ffm/supernode_puppet/blob/sysctl/modules/sysctl_conf/templates/sysctl.conf.erb

**Comment by christf** [comment]
@skorpy2009  was ist mit dem disable routing nach eth0 - das wollen wir doch auf den meisten servern.

**Comment by christf** [comment]
der Stand ist für mich ok und imo kann das nach production.
@t-8ch  siehst Du das auch so?

**Comment by skorpy2009** [comment]
https://github.com/freifunk-ffm/supernode_puppet/pull/18

**Comment by t-8ch** [comment]
:+1:

**Comment by skorpy2009** [comment]
merged freifunk-ffm/supernode_puppet#18 + merged it on to puppetmaster
fastd1 & 2 have it installed, still working

**Comment by skorpy2009** [comment]
Test on fastd1 with forced panic worked 👍 
Need to check if not to many reboots will occur

**Comment by skorpy2009** [comment]
fastd4 was installed automatically by puppet

**Comment by christf** [comment]
3, 5, 6 fehlen noch.

**Comment by skorpy2009** [comment]
6 gibt es nicht...

**Comment by skorpy2009** [comment]
fastd5 has it 👍 
fastd3 is still down 👎

**Comment by christf** [comment]
6 gibt es. das ist ein mit puppet aufgebauter babel-host...

**Comment by christf** [comment]
3 hat sie jetzt auch

**Comment by skorpy2009** [comment]
Fastd6 ist nix Babel!

**Comment by skorpy2009** [comment]
Es ist nicht klar ob die Server die Config intern behalten.

**Comment by t-8ch** [comment]
Beim  3er war ich das manuell  zum testen, weil alle anderen  Einstellungen scheinbar da waren

**Comment by skorpy2009** [comment]
Das ist aber bei allen Servern so anscheinend. https://github.com/freifunk-ffm/supernode_puppet/pull/18 Habe ich das auch mal reingepostet

**Comment by christf** [comment]
Du kannst natürlich einen anderen Server zusätzlich zum bestehenden fastd6 aufbauen und dann sagen das der neue nicht babel macht. Das ist dann so. Freut mich, das es einen Server mehr gibt.

Am 23. Oktober 2016 15:28:41 MESZ, schrieb skorpy2009 <notifications@github.com>:
>Fastd6 ist nix Babel!

Viele Grüße

Christof
-- 
Diese Nachricht wurde mit K-9 Mail gesendet.

**Comment by christf** [comment]
Woran machst du das fest?

Am 23. Oktober 2016 15:30:14 MESZ, schrieb skorpy2009 <notifications@github.com>:
>Es ist nicht klar ob die Server die Config intern behalten.

Viele Grüße

Christof
-- 
Diese Nachricht wurde mit K-9 Mail gesendet.

**Comment by skorpy2009** [comment]
https://map.ffm.freifunk.net/grafana/dashboard/db/fastd?var-instance=10.126.40.1&from=1477415605101&to=1477422187165

Besonders gut ist dies nach dem Neustart sichtbar, siehe oben.

**Comment by christf** [comment]
On Wed, Oct 26, 2016 at 09:26:10AM -0700, skorpy2009 wrote:
>https://map.ffm.freifunk.net/grafana/dashboard/db/fastd?var-instance=
>10.126.40.1&from=1477415605101&to=1477422187165
>
>Besonders gut ist dies nach dem Neustart sichtbar, siehe oben.
Was meinst Du? Was genau sollte sichtbar sein?

-- 
()  ascii ribbon campaign - against html e-mail
/\  against proprietary attachments

**Comment by skorpy2009** [comment]
https://github.com/freifunk-ffm/supernode_puppet/commit/34c7e6d6d98cc6bb444efdd3f43af01b7e0e8ce8

maybe this fixes the problem. 

Firewall relaoding could be the issue

**Comment by skorpy2009** [comment]
Problem gefunden: nf_conntrack wird erst durch die firewall geladen => sysctl ist schon lange fertig und ignoriert den eintrag oder nf_conntrack überschreibt ihn oder was weiß ich schon!

Lösung: nf_conntrack vorher laden! einfach nf_conntrack in die /etc/modules reinschreiben und es scheint gelöst zusein...

**Comment by skorpy2009** [comment]
@t-8ch Wie bekommen wir SAUBER nf_conntrack in die /etc/modules ?

**Comment by christf** [comment]
bitte in /etc/modules.d/nf_conntrack ablegen und nicht direkt /etc/modules editieren

**Comment by skorpy2009** [comment]
> bitte in /etc/modprobe.d/nf_conntrack ablegen und nicht direkt /etc/modules editieren
Ja, das war ja meine aussage mit sauber und so...

**Comment by t-8ch** [comment]
Das sollte doch eher nach /etc/modules-load.d/

**Comment by skorpy2009** [comment]
@t-8ch hast du einen Vorschlag außer der Hammer Methode? Weil einfach Datei in /etc/modules-load.d/nf_conntrack kann ja jeder 😂😳🙄😋.

**Comment by t-8ch** [comment]
Hö? Wieso Hammer?

**Comment by skorpy2009** [comment]
https://github.com/freifunk-ffm/supernode_puppet/commit/a5224757f37317ef0f88798b0268de51f32921a5

https://github.com/freifunk-ffm/supernode_puppet/commit/e3b8d524cb013fbcac6311a0f6e7a42bec1cb2e3

**Comment by christf** [comment]
ein traum. gehts jetzt?

**Comment by skorpy2009** [comment]
Also auf fastd4 geht es immer noch ned. Fehler noch ned gefunden...

net.nf_conntrack_max = 32008

**Comment by christf** [comment]
im letzten Monat waren keine negativn Auswirkungen mehr sichtbar  => das Thema ist erledigt.
