### ISSUE TITLE
VPN-Laufzeit-Pflege

### ISSUE THREAD

**Issue by christf** [freifunk-ffm/ToDo-Liste#9]
wie setzt man das transparent auf?

**Comment by christf** [comment]
@skorpy2009 @triplem @t-8ch @oszilloskop 
keine Ideen?

**Comment by oszilloskop** [comment]
Was ist mit "Laufzeit-Pflege" gemein und für wen soll sie wie transparent sein?

**Comment by christf** [comment]
Unsere VPN laufen regelmäßig aus und müssen manuell verlängert werden. Ich hätte gern ein ding, das dabei hilft diese Laufzeiten im Blick zu behalten.

Am 19. Oktober 2016 11:39:17 MESZ, schrieb oszilloskop <notifications@github.com>:
>Was ist mit "Laufzeit-Pflege" gemein und für wen soll sie wie
>transparent sein?

Viele Grüße

Christof
-- 
Diese Nachricht wurde mit K-9 Mail gesendet.

**Comment by skorpy2009** [comment]
Da wir in Zukunft den Traffic direkt in unserer Colo ausleiten, werden wir keine neuen Tunnel mehr brauchen und die aktuellen auslaufen lassen?
